import dropdownOptions from "../components/dropdownOptions";
export const forms = {
  b2b: [
    {
      label: "GSTIN/UIN of Recipient",
      name: "recipient_gstin",
      type: "text",
      placeholder: "Enter GSTIN or UIN of the recipient",
      tag: "input",
      required: true,
    },
    {
      label: "Receiver Name",
      name: "recipient_name",
      type: "select",
      placeholder: "Enter receiver name",
      tag: "select",
      required: true,
      options: dropdownOptions.receiverNames, // Assuming you have this in dropdownOptions
    },
    {
      label: "Invoice Number",
      name: "invoice_number",
      type: "text",
      placeholder: "Enter invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Invoice date",
      name: "invoice_date",
      type: "date",
      placeholder: "Select invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      tag: "input",
      required: true,
      placeholder: "Select place of supply",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Reverse Charge",
      name: "supply_attract_reverse_charge",
      type: "select",
      tag: "input",
      required: true,
      placeholder: "Select reverse charge applicability",
      options: dropdownOptions.reverseCharge,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "is_the_supply_eligible",
      type: "select",
      tag: "input",
      required: true,
      placeholder: "Select applicable tax rate %",
      options: dropdownOptions.taxrate,
    },
    {
      label: "Invoice Type",
      name: "supply_type",
      type: "select",
      placeholder: "Select invoice type",
      tag: "input",
      required: true,
      options: dropdownOptions.invoiceType,
    },
    {
      label: "E-Commerce GSTIN",
      name: "source",
      type: "text",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
      tag: "input",
      disabled: true,
    },
    {
      label: "Item Details",
      name: "items",
      type: "table",
      rows: ["Item 1"],
      columns: [
        {
          label: "Rate (%)",
          name: "rate",
          type: "select",
          options: ["5", "12", "18", "28"],
          default: "",
        },
        {
          label: "Taxable value (₹)",
          name: "taxable_value",
          type: "number",
          default: 0.0,
        },
        {
          label: "Integrated Tax (₹)",
          name: "integrated_tax",
          type: "number",
          default: 0.0,
          readOnly: true,
        },
        {
          label: "Central Tax (₹)",
          name: "central_tax",
          type: "number",
          default: 0.0,
          readOnly: true,
        },
        {
          label: "State Tax (₹)",
          name: "state_tax",
          type: "number",
          default: 0.0,
          readOnly: true,
        },
        {
          label: "Cess (₹)",
          name: "cess",
          type: "number",
          default: 0.0,
        },
        {
          label: "Invoice Value (₹)",
          name: "invoice_value",
          type: "number",
          default: 0.0,
          readOnly: true,
        },
      ],
    },
  ],
  B2CL: [
    {
      label: "Invoice Number",
      name: "invoice_no",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Invoice Date",
      name: "invoice_date",
      type: "date",
      required: true,
      tag: "input",
    },

    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "rate_of_tax",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.taxrate,
    },
    {
      label: "E-Commerce GSTIN",
      name: "source",
      type: "text",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
      tag: "input",
      disabled: true,
    },
  ],
  B2CS: [
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      required: true,
      options: dropdownOptions.placeOfSupply,
      tag: "select",
    },
    {
      label: "Applicable % of Tax Rate",
      name: "rate_of_tax",
      type: "select",
      required: true,
      tag: "input",
      options: dropdownOptions.taxrate,
    },
    {
      label: "E-Commerce GSTIN",
      name: "ecommerce_gstin",
      type: "text",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
      required: false,
      tag: "input",
      disabled: true,
    },
  ],

  SIXA: [
    {
      label: "Invoice no",
      name: "invoice_no",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Invoice date",
      name: "invoice_date",
      type: "date",
      required: true,
      tag: "input",
    },
    {
      label: "Port Code",
      name: "port_code",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Shipping Bill No./Bill of Export No",
      name: "shipping_bill_export_no",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Shipping Bill Date/Bill of Export Date",
      name: "invoice_no_export_date",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Total invoice value",
      name: "total_invoice_value",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "Supply Type",
      name: "supply_type",
      type: "select",
      placeholder: "Inter-State",
      required: true,
      tag: "select",
      options: dropdownOptions.supplyType, // assuming you have this in dropdownOptions
    },
    {
      label: "GST Payment",
      name: "gst_payment",
      placeholder: "With Payment Tax",
      type: "number",
      required: true,
      tag: "input",
    },
    {
      label: "Source",
      name: "source",
      type: "text",
      required: true,
      tag: "input",
    },
    {
      label: "IRN Date",
      name: "irn_date",
      type: "date",
      required: true,
      tag: "input",
    },
    {
      label: "Total invoice value(₹)",
      name: "is_the_supply_eligible",
      type: "text",
      required: true,
      tag: "input",
    },
  ],
  HSN: [
    {
      label: "HSN Type",
      name: "hsn",
      type: "select",
      required: true,
      placeholder: "Enter HSN Code",
      tag: "select",
      options: dropdownOptions.supplyType, // assuming you have this in dropdownOptions
    },
    {
      label: "HSN No",
      name: "hsn_no",
      type: "text",
      required: true,
      placeholder: "Enter HSN Code",
      tag: "input", 
    },
    {
      label: "Description",
      name: "description",
      type: "text",
      required: true,
      placeholder: "Enter Description",
      tag: "input",
    },
    {
      label: "UQC",
      name: "uqc",
      type: "select",
      required: true,
      options: dropdownOptions.uqcOptions, // assuming you have this in dropdownOptions
      tag: "select",
    },
    {
      label: "Total Quantity",
      name: "total_quantity",
      type: "number",
      required: true,
      placeholder: "Enter Total Quantity",
      tag: "input",
    },
    {
      label: "Total Value (₹)",
      name: "total_value",
      type: "number",
      required: true,
      placeholder: "Enter Total Value",
      tag: "input",
    },
  ],
  CDNR: [
    {
      label: "GSTIN/UIN of Recipient",
      name: "recipient_gstin",
      type: "text",
      required: true,
      placeholder: "Enter GSTIN/UIN of Recipient",
      tag: "input",
    },
    {
      label: "Receiver Name",
      name: "receiver_name",
      type: "text",
      required: true,
      placeholder: "Enter Receiver Name",
      tag: "input",
    },
    {
      label: "Note Number",
      name: "note_number",
      type: "text",
      required: true,
      placeholder: "Enter Note Number",
      tag: "input",
    },
    {
      label: "Note Date",
      name: "note_date",
      type: "date",
      required: true,
      placeholder: "Select Note Date",
      tag: "input",
    },
    {
      label: "Note Type",
      name: "note_type",
      type: "select",
      required: true,
      options: ["Credit", "Debit"],
      tag: "select",
    },
    {
      label: "Place Of Supply",
      name: "place_of_supply",
      type: "select",
      required: true,
      options: dropdownOptions.placeOfSupply,
      tag: "select",
    },
    {
      label: "Reverse Charge",
      name: "reverse_charge",
      type: "select",
      required: true,
      options: dropdownOptions.reverseCharge,
      placeholder: "Select Yes / No",
      tag: "select",
    },
    {
      label: "Note Supply Type",
      name: "note_supply_type",
      type: "select",
      required: true,
      options: ["Inter-State", "Intra-State"],
      tag: "select",
    }, 
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "text",
      required: true,
      placeholder: "Enter Applicable % of Tax Rate",
      tag: "input",
    },
  ],
  CDNUR: [
    {
      label: "UR Type",
      name: "ur_type",
      type: "select",
      required: true,
      options: ["B2CL", "Export With Payment", "Export Without Payment"],
      tag: "select",
    },
    {
      label: "Note Number",
      name: "note_number",
      type: "text",
      required: true,
      placeholder: "Enter Note Number",
      tag: "input",
    },
    {
      label: "Note Date",
      name: "note_date",
      type: "date",
      required: true,
      placeholder: "Select Note Date",
      tag: "input",
    },
    {
      label: "Note Type",
      name: "note_type",
      type: "select",
      required: true,
      options: ["Credit", "Debit"],
      tag: "select",
    },
    {
      label: "Place Of Supply",
      name: "place_of_supply",
      type: "select",
      required: true,
      options: dropdownOptions.placeOfSupply,
      tag: "select",
    }, 
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "text",
      required: true,
      placeholder: "Enter Applicable % of Tax Rate",
      tag: "input",
    },
  ],
  EXP: [
    {
      label: "Export Type",
      name: "export_type",
      type: "select",
      required: true,
      options: ["With Payment", "Without Payment"],
      tag: "select",
    },
    {
      label: "Invoice Number",
      name: "invoice_number",
      type: "text",
      required: true,
      placeholder: "Enter Invoice Number",
      tag: "input",
    },
    {
      label: "Invoice Date",
      name: "invoice_date",
      type: "date",
      required: true,
      placeholder: "Select Invoice Date",
      tag: "input",
    }, 
    {
      label: "Port Code",
      name: "port_code",
      type: "text",
      required: true,
      placeholder: "Enter Port Code",
      tag: "input",
    },
    {
      label: "Shipping Bill Number",
      name: "shipping_bill_number",
      type: "text",
      required: true,
      placeholder: "Enter Shipping Bill Number",
      tag: "input",
    },
    {
      label: "Shipping Bill Date",
      name: "shipping_bill_date",
      type: "date",
      required: true,
      placeholder: "Select Shipping Bill Date",
      tag: "input",
    },
  ],
  AT: [
    {
      label: "Place Of Supply",
      name: "place_of_supply",
      type: "select",
      required: true,
      options: dropdownOptions.placeOfSupply,
      tag: "select",
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "select",
      required: true,
      options: dropdownOptions.taxrate,
      tag: "select",
    },
  ],

  DOCS: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "Invoices for outward supply",
        "Invoices for inward supply from unregistered person",
        "Revised Invoice",
        "Debit Note",
        "Credit Note",
        "Receipt Voucher",
        "Payment Voucher",
        "Refund Voucher",
        "Delivery Challan for job work",
        "Delivery Challan for supply on approval",
        "Delivery Challan in case of liquid gas",
        "Delivery Challan in cases other than by way of supply (excluding at 5 no. 9 to 11)",
      ],
      columns: [
        {
          label: "Particular",
          name: "particular",
          type: "text",
          required: true,
          readOnly: true,
        },
        {
          label: "Sr. No. From",
          name: "sr_no_from",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Sr. No. To",
          name: "sr_no_to",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Total Number",
          name: "total_number",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Cancelled",
          name: "cancelled",
          type: "text",
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Net Issued",
          name: "net_issued",
          type: "text",
          readOnly: true,
        },
      ],
    },
  ],
  EXEMPT: [
    {
      tables: [
        {
          label: "",
          name: "tables",
          type: "table",
          rows: [
            "Intra-state supplies to registered person",
            "Intra-state supplies to unregistered person",
            "Inter-state supplies to registered person",
            "Inter-state supplies to unregistered person",
          ],
          columns: [
            {
              label: "Description",
              name: "description",
              type: "text",
              readOnly: true,
            },
            {
              label: "Nil Rated Supplies (₹)",
              name: "nil_rated_supplies",
              type: "number",
              default: 0.0,
            },
            {
              label: "Exempted (Other than Nil rated / non-GST supply) (₹)",
              name: "exempted_supplies",
              type: "number",
              default: 0.0,
            },
            {
              label: "Non-GST Supplies (₹)",
              name: "non_gst_supplies",
              type: "number",
              default: 0.0,
            },
          ],
        },
      ],
    },
  ],
  ATADJ: [
    {
      label: "Place Of Supply",
      name: "atadj_place_of_supply",
      type: "select",
      required: true,
      placeholder: "Enter Place Of Supply",
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "atadj_applicable_percent_tax_rate",
      type: "select",
      required: true,
      placeholder: "Enter Applicable % of Tax Rate",
      tag: "select",
      options: dropdownOptions.taxrate,
    },
    // {
    //   label: "Cess Amount",
    //   name: "atadj_cess_amount",
    //   type: "text",
    //   required: true,
    //   placeholder: "Enter Cess Amount",
    //   tag: "input",
    // },
  ],

  /* *************************
         AMENTMENT START      
  *****************************/
  b2ba: [
    {
      label: "GSTIN/UIN of Recipient",
      name: "recipient_gstin",
      type: "text",
      placeholder: "Enter GSTIN or UIN of the recipient",
      tag: "input",
      required: true,
    },
    {
      label: "Receiver Name",
      name: "recipient_name",
      type: "text",
      placeholder: "Enter receiver name",
      tag: "input",
      required: true,
    },
    {
      label: "Original Invoice Number",
      name: "original_invoice_number",
      type: "text",
      placeholder: "Enter original invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Original Invoice Date",
      name: "original_invoice_date",
      type: "date",
      placeholder: "Select original invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Revised Invoice Number",
      name: "revised_invoice_number",
      type: "text",
      placeholder: "Enter revised invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Revised Invoice Date",
      name: "revised_invoice_date",
      type: "date",
      placeholder: "Select revised invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Invoice Value",
      name: "invoice_value",
      type: "text",
      placeholder: "Enter invoice value",
      tag: "input",
      required: true,
    },
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      placeholder: "Select place of supply",
      tag: "input",
      required: true,
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Reverse Charge",
      name: "reverse_charge",
      type: "select",
      placeholder: "Select reverse charge applicability",
      tag: "input",
      required: true,
      options: dropdownOptions.reverseCharge,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "tax_rate",
      type: "select",
      placeholder: "Select applicable tax rate %",
      tag: "input",
      required: true,
      options: dropdownOptions.taxrate,
    },
    {
      label: "Invoice Type",
      name: "invoice_type",
      type: "select",
      placeholder: "Select invoice type",
      tag: "input",
      required: true,
      options: dropdownOptions.invoiceType,
    },
    {
      label: "E-Commerce GSTIN",
      name: "ecommerce_gstin",
      type: "text",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
      tag: "input",
      required: true,
    },
  ],

  b2cla: [
    {
      label: "Original Invoice Number",
      name: "original_invoice_number",
      type: "text",
      placeholder: "Enter original invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Original Invoice Date",
      name: "original_invoice_date",
      type: "date",
      placeholder: "Select original invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Original Place Of Supply",
      name: "original_pos",
      type: "select",
      placeholder: "Select original place of supply",
      tag: "input",
      required: true,
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Revised Invoice Number",
      name: "revised_invoice_number",
      type: "text",
      placeholder: "Enter revised invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Revised Invoice Date",
      name: "revised_invoice_date",
      type: "date",
      placeholder: "Select revised invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Invoice Value",
      name: "invoice_value",
      type: "text",
      placeholder: "Enter invoice value",
      tag: "input",
      required: true,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "tax_rate",
      type: "select",
      placeholder: "Select applicable tax rate %",
      tag: "input",
      required: true,
      options: dropdownOptions.taxrate,
    },
    {
      label: "E-Commerce GSTIN",
      name: "ecommerce_gstin",
      type: "text",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
      tag: "input",
      required: true,
    },
  ],

  expa: [
    {
      label: "Export Type",
      name: "export_type",
      type: "select",
      placeholder: "Select export type",
      tag: "input",
      required: true,
      options: dropdownOptions.exportType, // Ensure this exists in your dropdownOptions
    },
    {
      label: "Original Invoice Number",
      name: "original_invoice_number",
      type: "text",
      placeholder: "Enter original invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Original Invoice Date",
      name: "original_invoice_date",
      type: "date",
      placeholder: "Select original invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Revised Invoice Number",
      name: "revised_invoice_number",
      type: "text",
      placeholder: "Enter revised invoice number",
      tag: "input",
      required: true,
    },
    {
      label: "Revised Invoice Date",
      name: "revised_invoice_date",
      type: "date",
      placeholder: "Select revised invoice date",
      tag: "input",
      required: true,
    },
    {
      label: "Invoice Value",
      name: "invoice_value",
      type: "text",
      placeholder: "Enter invoice value",
      tag: "input",
      required: true,
    },
    {
      label: "Port Code",
      name: "port_code",
      type: "text",
      placeholder: "Enter port code",
      tag: "input",
      required: true,
    },
    {
      label: "Shipping Bill Number",
      name: "shipping_bill_number",
      type: "text",
      placeholder: "Enter shipping bill number",
      tag: "input",
      required: true,
    },
    {
      label: "Shipping Bill Date",
      name: "shipping_bill_date",
      type: "date",
      placeholder: "Select shipping bill date",
      tag: "input",
      required: true,
    },
  ],

  b2csa: [
    {
      label: "Financial Year",
      name: "financial_year",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.financialYear,
    },
    {
      label: "Original Month",
      name: "original_month",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.months,
    },
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Type",
      name: "supply_type",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.b2csType,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.taxrate,
    },
    {
      label: "E-Commerce GSTIN",
      name: "ecommerce_gstin",
      type: "text",
      required: false,
      tag: "input",
      placeholder: "Enter E-Commerce GSTIN (if applicable)",
    },
  ],
  cdnra: [
    {
      label: "GSTIN/UIN of Recipient",
      name: "gstin_uin",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter GSTIN/UIN",
    },
    {
      label: "Receiver Name",
      name: "receiver_name",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Receiver Name",
    },
    {
      label: "Original Note Number",
      name: "original_note_number",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Original Note Number",
    },
    {
      label: "Original Note Date",
      name: "original_note_date",
      type: "date",
      required: true,
      tag: "input",
    },
    {
      label: "Revised Note Number",
      name: "revised_note_number",
      type: "text",
      required: false,
      tag: "input",
      placeholder: "Enter Revised Note Number",
    },
    {
      label: "Revised Note Date",
      name: "revised_note_date",
      type: "date",
      required: false,
      tag: "input",
    },
    {
      label: "Note Type",
      name: "note_type",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.noteType, // e.g., ["Credit", "Debit"]
    },
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Reverse Charge",
      name: "reverse_charge",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.reverseCharge,
    },
    {
      label: "Note Supply Type",
      name: "note_supply_type",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.invoiceType, // if different, create another like dropdownOptions.noteSupplyType
    },
    {
      label: "Note Value",
      name: "note_value",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Note Value",
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.taxrate,
    },
  ],
  cdnura: [
    {
      label: "UR Type",
      name: "ur_type",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.urType, // Example: ["Export", "Unregistered", etc.]
    },
    {
      label: "Original Note Number",
      name: "original_note_number",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Original Note Number",
    },
    {
      label: "Original Note Date",
      name: "original_note_date",
      type: "date",
      required: true,
      tag: "input",
    },
    {
      label: "Revised Note Number",
      name: "revised_note_number",
      type: "text",
      required: false,
      tag: "input",
      placeholder: "Enter Revised Note Number",
    },
    {
      label: "Revised Note Date",
      name: "revised_note_date",
      type: "date",
      required: false,
      tag: "input",
    },
    {
      label: "Note Type",
      name: "note_type",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.noteType, // Example: ["Credit", "Debit"]
    },
    {
      label: "Place Of Supply",
      name: "pos",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Note Value",
      name: "note_value",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Note Value",
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.taxrate,
    },
  ],
  ata: [
    {
      label: "Financial Year",
      name: "financial_year",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.financialYear,
    },
    {
      label: "Original Month",
      name: "original_month",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.months,
    },
    {
      label: "Original Place Of Supply",
      name: "original_pos",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply,
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_rate",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.taxrate,
    },

    {
      label: "Gross Advance Received",
      name: "gross_advance_received",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Gross Advance Received",
    },
  ],

  ecoa: [
    {
      label: "Nature of Supply",
      name: "nature_of_supply",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.natureOfSupply, // Example: ["Inter-State", "Intra-State"]
    },
    {
      label: "Financial Year",
      name: "financial_year",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.financialYear,
    },
    {
      label: "Original Month/Quarter",
      name: "original_month_quarter",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.months, // Or use `dropdownOptions.quarters` if applicable
    },
    {
      label: "Original GSTIN of E-Commerce Operator",
      name: "original_gstin_ecom",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Original GSTIN",
    },
    {
      label: "Revised GSTIN of E-Commerce Operator",
      name: "revised_gstin_ecom",
      type: "text",
      required: false,
      tag: "input",
      placeholder: "Enter Revised GSTIN",
    },
    {
      label: "E-Commerce Operator Name",
      name: "ecom_operator_name",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Name",
    },
    {
      label: "Revised Net Value of Supplies",
      name: "revised_net_value",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Net Value",
    },
  ],

  ATADJA: [
    {
      label: "Financial Year",
      name: "financial_year",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.financialYear,
    },
    {
      label: "Original Month",
      name: "original_month",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.months,
    },
    {
      label: "Original Place Of Supply",
      name: "original_place_of_supply",
      type: "select",
      required: true,
      tag: "select",
      options: dropdownOptions.placeOfSupply, // Make sure this exists
    },
    {
      label: "Applicable % of Tax Rate",
      name: "applicable_tax_percentage",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Applicable Tax %",
    },
    {
      label: "Rate",
      name: "rate",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Rate",
    },
    {
      label: "Gross Advance Adjusted",
      name: "gross_advance_adjusted",
      type: "text",
      required: true,
      tag: "input",
      placeholder: "Enter Gross Advance",
    },
    {
      label: "Cess Amount",
      name: "cess_amount",
      type: "text",
      required: false,
      tag: "input",
      placeholder: "Enter Cess Amount",
    },
  ],

  FOUR: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "(A) Supplies made to unregistered persons (B2C)",
        "(B) Supplies made to registered persons (B2B)",
        "(C) Zero rated supply (Export) on payment of tax (Except supplies to SET)",
        "(D)Supplies to SEZ on payment of tax",
        "(E) Deemed Exports",
        "(F) Advances on which tax has ben paid but invoice has not been issued (not covered under (A) to (E) Above)",
        "(G) Inward supplies on which tax is to be paid on the reverse charge basis",
        "(G1) Supplies on which e-commerce operator is required to pay tax as per section 9(5) (including amendments, if any) [E-commerce operator to report]",
        "(H) Sub-total (A to G1 above)",
        "(1) Credit notes issued in respect of transactions specified in (B) to (E) above (-)",
        "(3) Debit notes issued in respect of transactions specified in (8) to (E) above (+)",
        "(K) Supplies/tax declared through Amendments (+)",
        "(1) Supplies/tax reduced through Amendments (-)",
        "(M) Sub total (I to L above)",
        "(N) Supplies and advances on which tax is to be paid (H+ M) above",
      ],
      columns: [
        {
          label: "Particular",
          name: "particular",
          type: "text",
          required: true,
          readOnly: true,
        },
        {
          label: "Sr. No. From",
          name: "sr_no_from",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Sr. No. To",
          name: "sr_no_to",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Total Number",
          name: "total_number",
          type: "text",
          required: true,
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Cancelled",
          name: "cancelled",
          type: "text",
          validation: {
            pattern: "^[0-9]+$",
            message: "Only numbers are allowed",
          },
        },
        {
          label: "Net Issued",
          name: "net_issued",
          type: "text",
          readOnly: true,
        },
      ],
    },
  ],
  FIVE: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "(A) Zero rated supply (Export) without payment of tax",
        "(B) Supply to SEZ without payment of tax",
        "(C) Supplies on which tax is to be paid by the recipient on reverse charge basis",
        "(C1) Supplies on which tax is to be paid by e-commerce operators as per section 9(5) [Supplier to report]",
        "(D) Exempted",
        "(E) Nil Rated",
        "(F) Non-GST supply (includes 'no supply')",
        "(G) Sub total (A to F above)",
        "(H) Credit notes issued in respect of transactions specified in (A to F) above (-)",
        "(I) Debit notes issued in respect of transactions specified in (A to F) above (+)",
        "(J) Supplies declared through Amendments (+)",
        "(K) Supplies reduced through Amendments (-)",
        "(L) Sub total (H to K)",
        "(M) Turnover on which tax is not to be paid (G + L above)",
        "(N) Total Turnover (including advances) (4N + 5M - 4G - 4G1 above)",
      ],
    },
  ],
  SIX: [
    {
      "label": "Details of ITC availed during the financial year",
      "name": "itc_details",
      "type": "table",
      "documentTypes": [
        "(A) Total amount of input tax credit availed through FORM GSTR-3B (sum total of Table 4A of FORM GSTR-3B)",
        "(B) Inward supplies (other than imports and inward supplies liable to reverse charge but includes services received from SEZs)",
        "(C) Inward supplies received from unregistered persons liable to reverse charge (other than B above) on which tax is paid & ITC availed",
        "(D) Inward supplies received from registered persons liable to reverse charge (other than B above) on which tax is paid and ITC availed",
        "(E) Import of goods (including supplies from SEZ)",
        "(F) Import of services (excluding inward supplies from SEZ)",
        "(G) Input Tax credit received from ISD",
        "(H) Amount of ITC reclaimed (other than B above) under the provisions of the Act",
        "(I) Sub total (B to H above)",
        "(J) Difference (I - A above)",
        "(K) Transition Credit through TRAN-I (including revisions if any)",
        "(L) Transition Credit through TRAN-II",
        "(N) Any other ITC availed but not specified above",
        "(N) Sub total (K to N above)",
        "(O) Total ITC availed (A + N above)"
      ], 
      "subRows": {
        "(B) Inward supplies (other than imports and inward supplies liable to reverse charge but includes services received from SEZs)": [
          "Inputs",
          "Capital goods",
          "Input Services"
        ],
        "(C) Inward supplies received from unregistered persons liable to reverse charge (other than B above) on which tax is paid & ITC availed": [
          "Inputs",
          "Capital goods",
          "Input Services"
        ],
        "(D) Inward supplies received from registered persons liable to reverse charge (other than B above) on which tax is paid and ITC availed": [
          "Inputs",
          "Capital goods",
          "Input Services"
        ],
        "(E) Import of goods (including supplies from SEZ)": [
          "Capital goods",
          "Inputs"
        ]
      }
    }
  ],
  SEVEN: [
    {
      "label": "Details of ITC Reversed and Ineligible ITC for the financial year",
      "name": "itc_reversed_details",
      "type": "table",
      "sections": [
        "(A) As per Rule 37",
        "(B) As per Rule 39",
        "(C) As per Rule 42",
        "(D) As per Rule 43",
        "(E) As per section 17(5)",
        "(F) Reversal of TRAN-1 credit",
        "(G) Reversal of TRAN-11 credit",
        "(H1) Other reversals (pl. specify)",
        "(1) Total ITC Reversed (Sum of A to H above)",
        "(2) Net ITC Available for Utilization (60 - 71)"
      ],
      "taxColumns": [
        "integrated_tax",
        "central_tax",
        "state_tax",
        "cess"
      ],
      "specialColumns": {
        "(F) Reversal of TRAN-1 credit": {
          "disabled": ["integrated_tax", "cess"]
        },
        "(G) Reversal of TRAN-11 credit": {
          "disabled": ["integrated_tax", "cess"]
        },
        "(1) Total ITC Reversed (Sum of A to H above)": {
          "readonly": true,
          "calculate": "sum(A-H)"
        },
        "(2) Net ITC Available for Utilization (60 - 71)": {
          "readonly": true,
          "calculate": "reference"
        }
      }
    }
  ]
,
  EIGHT: [
    { 
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "(A) ITC as per GSTR-2B [Table 3(I) thereof]",
        "(B) ITC as per sum total of 6(B) and 6(H) above",
        "(C) ITC on inward supplies (other than imports and inward supplies liable to reverse charge but includes services received from SEZs) received during the financial year but availed in the next financial year upto specified period",
        "(D) Difference [A – (B + C)]",
        "(E) ITC available but not availed",
        "(F) ITC available but ineligible",
        "(G) IGST paid on import of goods (including supplies from SEZ)",
        "(H) IGST credit availed on import of goods (as per 6(E) above)",
        "(I) Difference (G - H)",
        "(J) ITC available but not availed on import of goods (Equal to I)",
        "(K) Total ITC to be lapsed in current financial year (E + F + J)",
      ],
    }, 
  ],
   NINE: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "Integrated Tax",
        "Central Tax",
        "State/UT Tax",
        "Cess",
        "Interest",
        "Late Fees",
        "Penalty",
        "Others",
      ],
    },
  ],
  GSTR9_10_11_12_13: [
    {
      label: "Amendments and ITC Details",
      name: "tables",
      type: "table",
      documentTypes: [
        "10. Supplies / tax declared through Amendments (+) (net of debit notes)",
        "11. Supplies / tax reduced through Amendments (-) (net of credit notes)",
        "12. Reversal of ITC availed during previous financial year",
        "13. ITC availed for the previous financial year",
        "Total turnover (5N + 10 - 11)",
      ],
    },
  ],
  FOURTEEN: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "Integrated Tax",
        "Central Tax",
        "State/UT Tax",
        "Cess",
        "Interest",
      ],
    },
  ],

  FIFTEEN: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "(A) Total Refunds Claimed",
        "(B) Total Refunds sanctioned",
        "(C) Total Refunds rejected",
        "(D) Total Refunds pending",
        "(E) Total demand of taxes",
        "(F) Total taxes paid in respect of E above",
        "(G) Total paid in respect of E above",
      ],
    },
  ],
  SIXTEEN: [
    {
      label: "Documents Issued",
      name: "tables",
      type: "table",
      documentTypes: [
        "(A) Supply received from composition taxpayers",
        "(B) Deemed supply under section 143",
        "(C) Goods sent on approval basis but not returned",
      ],
    },
  ],
};
