// src/constants/dropdownOptions.js
const dropdownOptions = {
  b2csType: ["E", "OE"],
  reverseCharge: ["Y", "N"],
  invoiceType: [
    "Regular B2B",
    "SEZ supplies with payment",
    "SEZ supplies without payment",
    "Deemed Export",
    "Intra-State Supplies attracting IGST"
  ],
  placeOfSupply: [
    "01-Andaman and Nicobar Islands",
    "02-Andhra Pradesh",
    "03-Arunachal Pradesh",
    "04-Assam",
    "05-Bihar",
    "06-Chandigarh",
    "07-Chhattisgarh",
    "08-Dadra and Nagar Haveli and Daman and Diu",
    "09-Delhi",
    "10-Goa",
    "11-Gujarat",
    "12-Haryana",
    "13-Himachal Pradesh",
    "14-Jammu and Kashmir",
    "15-Jharkhand",
    "16-Karnataka",
    "17-Kerala",
    "18-Ladakh",
    "19-Lakshadweep",
    "20-Madhya Pradesh",
    "21-Maharashtra",
    "22-Manipur",
    "23-Meghalaya",
    "24-Mizoram",
    "25-Nagaland",
    "26-Odisha",
    "27-Puducherry",
    "28-Punjab",
    "29-Rajasthan",
    "30-Sikkim",
    "31-Tamil Nadu",
    "32-Telangana",
    "33-Tripura",
    "34-Uttar Pradesh",
    "35-Uttarakhand",
    "36-West Bengal"
  ],
  rate: ["0%", "0.25%", "3%", "5%", "12%", "18%", "28%"],
  taxrate: ["65.00"],

  // ✅ Flat array as requested
  uqcOptions: [
    "BAG - BAGS",
    "BAL - BALE",
    "BDL - BUNDLES",
    "BKL - BUCKLES",
    "BOU - BILLIONS OF UNITS",
    "BOX - BOX",
    "BTL - BOTTLES",
    "BUN - BUNCHES",
    "CAN - CANS",
    "CBM - CUBIC METER",
    "CCM - CUBIC CENTIMETER",
    "CMS - CENTIMETERS",
    "CTN - CARTONS",
    "DOZ - DOZENS",
    "DRM - DRUMS",
    "GGK - GREAT GROSS",
    "GGR - GROSS GROSS",
    "GMS - GRAMS",
    "GRS - GROSS",
    "GYD - GROSS YARDS",
    "KGS - KILOGRAMS",
    "KLR - KILOLITRE",
    "KME - KILOMETRE",
    "LTR - LITRE",
    "MGM - MILLIGRAMS",
    "MLT - MILLILITRE",
    "MTR - METERS",
    "MTS - METRIC TONS",
    "NOS - NUMBERS",
    "PAC - PACKS",
    "PCS - PIECES",
    "PRS - PAIRS",
    "QTL - QUINTAL",
    "ROL - ROLLS",
    "SET - SETS",
    "SQF - SQUARE FEET",
    "SQM - SQUARE METERS",
    "TBS - TABLETS",
    "TGM - TEN GRAMS",
    "THD - THOUSANDS",
    "TON - TONNES",
    "TUB - TUBES",
    "UGS - USAGES",
    "UNT - UNITS",
    "YDS - YARDS"
  ],
  receiverNames: [
  "Receiver 1",
  "Receiver 2",
  "Receiver 3", 
  // Add more receiver names as needed
],
supplyType: [
  "B2B Supplies",
  "B2C Supplies"
],
};

export default dropdownOptions;
