import React from 'react';

const GSTR2B = () => {
  return (
    <div className="min-h-screen bg-gray-100 p-6">
      {/* Header */}
      <div className=" shadow-md p-4 rounded-md">
        <h2 className="text-xl font-semibold text-blue-700">GSTR-2B: AUTO-DRAFTED ITC STATEMENT</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 mt-3 text-sm text-gray-700">
          <div><strong>GSTIN:</strong> 09AHTPR0931C1ZG</div>
          <div><strong>Legal Name:</strong> RADHEYKRISHNA SINGH RATHORE</div>
          <div><strong>Trade Name:</strong> Radheykrishna Rathore Consulting Services</div>
          <div><strong>Financial Year:</strong> 2025-26</div>
          <div><strong>Return Period:</strong> June</div>
          <div><strong>Status:</strong> Generation Failed</div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mt-6 border-b border-gray-300">
        <button className="px-4 py-2 text-blue-700 border-b-2 border-blue-700 font-semibold">SUMMARY</button>
        <button className="px-4 py-2 text-gray-600">ALL TABLES</button>
        <button className="ml-auto px-4 py-2 text-sm text-blue-600 hover:underline">View Advisory</button>
      </div>

      {/* Error Box */}
      <div className="mt-6 bg-red-100 border border-red-400 text-red-700 px-6 py-4 rounded-md text-sm">
        <p className="font-semibold mb-2">Error!</p>
        <p>GSTR-2B could not be generated by the System. Kindly configure your GSTR-2B manually by clicking Generate GSTR-2B button available at IRIS Dashboard &gt; ITC Summary page.</p>
        <p className="mt-2">Attention: System is not able to generate GSTR-2B for the current return period due to any one of the following circumstances:</p>
        <ul className="list-disc list-inside mt-2">
          <li>Return is not filed for previous GSTR-1/5 return period</li>
          <li>GSTR-6 is not filed for previous return period</li>
          <li>No, B2B, CDN or IMPG inward and current return period is not a quarter ending month</li>
        </ul>
      </div>

      {/* Back Button */}
      <div className="mt-6">
        <button className="bg-gray-300 hover:bg-gray-400 text-gray-800 px-6 py-2 rounded shadow-sm">BACK TO DASHBOARD</button>
      </div>
    </div>
  );
};

export default GSTR2B;
